name            'dlovitch-etckeeper'
version         '0.1.0'
source          'git://github.com/dlovitch/puppet-etckeeper'
author          'David Lovitch'
summary         'Puppet etckeeper Module'
description     'Puppet etckeeper module, mostly for Debian/Ubuntu using mercurial.'
project_page    'http://github.com/dlovitch/puppet-etckeeper'